@url = http://localhost:8000
 
### base route
{{url}}/login

### LOGIN HENDRICK
POST {{url}}/login
content-type: application/json
 
{
    "email": "hd@gmail.com"
}
 
### LOGIN ANDREA
POST {{url}}/login
content-type: application/json
 
{
    "email": "andrea@gmail.com",
    "safeOriginCode": "12345678",
    "password": "an123"
}

### register me
POST {{url}}/register
content-type: application/json
 
{
    "firstName": "Andrea",
    "lastName": "lopez",
    "email": "andrea@gmail.com",
    "password": "an123",
    "language": "Deutsch",
    "nationality": "German",
    "safeOriginCode": "12345678",
    "confimationCode": "",
    "imagePublicId":"cld-sample"
}

### GET CURRENT USER
{{url}}/current-user

### GET ALL USERS
{{url}}/users

### GET USER ACCOUNT
{{url}}/users/632c163b107b22583ae88005

### GET USER ACCOUNT
{{url}}/andrea

### LOGOUT GET
{{url}}/logout


### RATE USER 
POST {{url}}/rate-us
content-type: application/json
 
{
    "email": "andrea@gmail.com",
    "feedback": "hi",
    "firstName":"Andrea",
    "lastName":"lopez"
}

### GET state and Deutchland fragen
{{url}}/all-questions/bremen

### UPDATE A USER
PUT {{url}}/update/632c163b107b22583ae88005
content-type: application/json

{
    "language": "deutsch"
}
