@url = http://localhost:8000
 
### base route
{{url}}/login

### LOGIN HENDRICK
POST {{url}}/login
content-type: application/json
 
{
    "email": "hd@gmail.com"
}
 
### LOGIN ANDREA
POST {{url}}/login
content-type: application/json
 
{
    "email": "andrea@gmail.com",

    "password": "an123",
    "safeOriginCode" :"12345678"

}

### register me
POST {{url}}/register
content-type: application/json
 
{
    "firstName": "Mezekir",
    "lastName": "Abraham",
    "email": "dimoabr@gmail.com",
    "password": "an123",
    "language": "English",
    "nationality": "Eritrean",
    "safeOriginCode": "12345678",
    "confimationCode": "12335545646"
}

### GET CURRENT USER
{{url}}/current-user

### LOGOUT GET
{{url}}/logout


### RATE USER 
POST {{url}}/rate-us
content-type: application/json
 
{
    "email": "andrea@gmail.com",
    "feedback": "hi",
    "firstName":"Andrea",
    "lastName":"lopez"
}